<div class="page-header">
    <h1>Auditorias do Sistema</h1>
</div>
<?php View::content() ?>
<h3 style="margin-bottom: 0px;">Usuarios do Sistema</h3>
<?php
    $dt = new DataTable($usuarios);
    $dt->addHeaders('id', 'Login', 'Nomes');
    $dt->addHeaders('<span style="font-size:11px">Ações Realizadas</span>');
    $dt->addHeaders('Examinar');
    $dt->addFields('id', 'login', 'nombres', 'num_acciones');
    $dt->imgLink('figuras/ver.png', 'admin/auditorias/usuario');
    echo $dt->render('class="table table-bordered table-striped"');
?>
