<?php
if (isset($contenidos) and $contenidos != false) { ?>
			<div class="item-large-content">
				<div class="item-header">
					<h2 class="pull-left"><?php echo $contenidos->subtitulo ?></h2>
					<div class="clearfix"></div>
				</div>
				<p><?php echo $contenidos->contenido ?></p>
			</div>
		<?
		}
?>
<br>
<h2>Todos os campos são obrigatórios.</h2>
<form class="form-horizontal" action="/agendar" method="post">
<input type="hidden" name="url" value="<?php echo $_SERVER['REQUEST_URI'] ?>" >
	<div class="form-group">
		<label for="Nome" class="col-sm-2 control-label">Nome</label>
		<div class="col-sm-10">
			<input type="text" name="nome" class="form-control" id="nome" placeholder="Nome">
		</div>
	</div>
	<div class="form-group">
		<label for="Sexo" class="col-sm-2 control-label">Sexo</label>
		<div class="checkbox">
			<label>
				<input id="sexo" name="sexo" type="radio" value="Masculino" required="required"> Masculino
			</label>
			<label>
				<input id="sexo" name="sexo" type="radio" value="Femenino" required="required"> Femenino
			</label>
		</div>
	</div>
	<div class="form-group">
		<label for="Nome" class="col-sm-2 control-label">Data de Nacimento</label>
		<div class="col-sm-4">
			<input type="date" name="datanacimento" class="form-control" id="datanacimento" placeholder="Data de Nacimento">
		</div>
	</div>
	<div class="form-group">
		<label for="email" class="col-sm-2 control-label">Email</label>
		<div class="col-sm-10">
			<input type="email" name="email" class="form-control" id="email" placeholder="Email">
		</div>
	</div>
	<div class="form-group">
		<label for="ConfirmEmail" class="col-sm-2 control-label">Confirma seu E-mail</label>
		<div class="col-sm-10">
			<input type="email" name="email1" class="form-control" id="ConfirmEmail" placeholder="Confirme seu E-mail">
		</div>
	</div>
	<div class="form-group">
		<label for="País" class="col-sm-2 control-label">País</label>
		<div class="col-sm-10">
			<input type="text" name="pais" class="form-control" id="pais" placeholder="País">
		</div>
	</div>
	<div class="form-group">
		<label for="estado" class="col-sm-2 control-label">Estado</label>
		<div class="col-sm-10">
			<input type="text" name="estado" class="form-control" id="estado" placeholder="Estado">
		</div>
	</div>
	<div class="form-group">
		<label for="horario" class="col-sm-2 control-label">Escreva os dias e horários de sua preferência</label>
		<div class="col-sm-10">
			<input type="text" name="horario" class="form-control" id="horario" placeholder="Horario de Preferência">
		</div>
	</div>
	<div class="form-group">
		<label for="horario" class="col-sm-2 control-label">Escolha a opção de atendimento Online:</label>
		<div class="checkbox">
			<label>
				<input id="atendimento" name="atendimento" type="radio" value="Atendimento Terapêutico via vídeo, Áudio ou por Skype" required="required"> Atendimento Terapêutico via vídeo, Áudio ou por Skype
			</label>
			<label>
				<input id="atendimento" name="atendimento" type="radio" value="Atendimento via E-mail, WhatsApp ou Telefone" required="required"> Atendimento via E-mail, WhatsApp ou Telefone
			</label>
		</div>
	</div>
	<div class="form-group">
		<label for="horario" class="col-sm-2 control-label">Explique, resumidamente, os motivos de você procurar por terapia. </label>
		<div class="col-sm-10">
			<textarea name="menssagem" cols="100" rows="5"></textarea>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-default">Guardar</button>
		</div>
	</div>
</form>
<h3>Opções de Pagamento</h3>
<div class="row">
	<div class="col-md-6">
		<h3 style="text-align: center;">Page Seguro</h3>
		<!-- INICIO FORMULARIO BOTAO PAGSEGURO -->
		<form style="text-align: center;" action="https://pagseguro.uol.com.br/checkout/v2/cart.html?action=add" method="post">
		<!-- NÃO EDITE OS COMANDOS DAS LINHAS ABAIXO -->
		<input type="hidden" name="itemCode" value="DBB88B3CD3D3D40884473FA4E1C3D096" />
		<input type="image" src="https://stc.pagseguro.uol.com.br/public/img/botoes/pagamentos/209x48-pagar-assina.gif" name="submit" alt="Pague com PagSeguro - é rápido, grátis e seguro!" />
		</form>
		<!-- FINAL FORMULARIO BOTAO PAGSEGURO -->
	</div>
	<div class="col-md-6">
		<h3 style="text-align: center;">Transferencia Bancaria</h3>
		<p style="text-align: center;"><strong>Bradesco</strong> <br /> AG: 3011-2 <br /> C/C 24852-5</p>
	</div>
</div>
<br>



