<div class="page-header">
    <h1><?php eh($titulo) ?></h1>
</div>
<div class="row">
    <div class="span3">
        <?php View::partial('backend/menus/menus') ?>
    </div>
    <div class="span8 span-derecho" >
        <div id="res-form-ajax"><?php View::content() ?></div>
        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
        <?php //echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
        <?php echo Form::hidden('menu.id') ?>
        <div class="control-group">
            <label class="control-label" for="menu_menu_id">Menu Pai : </label>
            <div class="controls">
                <?php echo Form::dbSelect('menu.menus_id', 'nombre', array('menus', 'find', 'activo = 1'), 'Ninguno') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="menu_recursos_id">Recurso a que Accede : </label>
            <div class="controls">
                <?php echo Form::dbSelect('menu.recursos_id', 'recurso') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="menu_nombre">Texto a Mostrar : </label>
            <div class="controls">
                <?php echo Form::text('menu.nombre') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="menu_url">Url do Menu : </label>
            <div class="controls">
                <?php echo Form::text('menu.url') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="menu_posicion">Posição do Menu : </label>
            <div class="controls">
                <?php echo Form::text('menu.posicion') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="menu_clases">Clases do Menu : </label>
            <div class="controls">
                <?php echo Form::text('menu.clases') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="menu_visible_en">Visible Em : </label>
            <div class="controls" style="margin-left: 210px">
                <label class="radio" style="white-space: nowrap">
                    <?php echo Form::radio('menu.visible_en', '1') ?>
                    Só na Aplicação, fora do Backend
                </label>
                <label class="radio">
                    <?php echo Form::radio('menu.visible_en', '2') ?>
                    Só no Backend
                </label>
                <label class="radio">
                    <?php echo Form::radio('menu.visible_en', '3') ?>
                    En qualquier parte do sistema
                </label>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="menu_activo">Ativo (Visible) : </label>
            <div class="controls">
                <?php echo Form::select('menu.activo', array('1' => 'Sim', '0' => 'Não')) ?>
                </div>
            </div>
            <div class="form-actions">
            <?php echo Form::submit('Guardar', 'class="btn btn-primary"') ?>
            <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
                </div>
        <?php echo Form::close() ?>
    </div>
</div>
<script type="text/javascript" >
    $(function(){
        $("#menu_recursos_id").live('change',function(){
            var recurso = $('option:selected',this).text();
            $("#menu_url").val(recurso.replace('/*',''));
        });
    });
</script>