<div class="page-header">
    <h1>Criar Pastas</h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<?php
View::partial('website/barra_superior_listas', FALSE, array('texto' => 'Nova Pasta','opciones'=>FALSE));
?>
<?php
//$archivos=1;
  $dt = new DataTable($carpetas);
  $dt->addHeaders('N&ordm;','Nombre','Descripcion','Creado','Modificado','Editar');
  $dt->addFields('id','nombre','descripcion','created_at','modified_in');
  /*$dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png','website/carpetas/activar|website/carpetas/desactivar', '', 'activo');*/
  $dt->imgLink('figuras/editar.png', 'website/carpetas/editar');
  /*$dt->imgLinkConfirm('figuras/eliminar.png', 'website/carpetas/eliminar', '', '¿Realmente desea eliminar esta carpeta?');*/
  echo $dt->render('class="table table-bordered table-striped"');
?>
