<!-- Load TinyMCE -->
<script type="text/javascript" src="/javascript/tinymce/tinymce.min.js"></script>
<!--<script type="text/javascript">
    tinymce.init({
        selector: "#mytextarea"
    });
</script>-->
<!-- /TinyMCE -->
<!--
<!DOCTYPE html>
<html>
<head>
  <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
  <script>tinymce.init({ selector:'textarea' });</script>
</head>
<body>
  <textarea>Easy! You should check out MoxieManager!</textarea>
</body>
</html>
-->

<script type="text/javascript">
    tinymce.init({
        language : "pt_BR",
        selector: ".tinymce",
        theme: "modern",
        fontsize_formats: "8pt 10pt 12pt 14pt 18pt 24pt 36pt 42pt",
        width: '100%',
        height: 300,
        plugins: [
             "advlist autolink link image lists charmap print preview hr anchor pagebreak",
             "searchreplace wordcount visualblocks visualchars code insertdatetime media nonbreaking",
             "table contextmenu directionality emoticons paste textcolor filemanager"
       ],
       image_advtab: true,
       toolbar: "undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | styleselect forecolor backcolor | link unlink anchor | image media | print preview code | sizeselect | fontselect | fontsizeselect",

       external_filemanager_path:"/javascript/responsivefilemanager/responsivefilemanager/",
       filemanager_title:"Responsive Filemanager" ,
       external_plugins: { "filemanager" : "/javascript/responsivefilemanager/responsivefilemanager/plugin.min.js"}
    });
</script>
<!--<script type="text/javascript">
    tinymce.init({
        language : "pt_BR",
        selector: "textarea",theme: "modern",width: 680,height: 100,
        fontsize_formats: "8pt 10pt 12pt 14pt 18pt 24pt 36pt 42pt",
        plugins: [
            "code",
             "advlist autolink link image lists charmap print preview hr anchor pagebreak",
             "searchreplace wordcount visualblocks visualchars insertdatetime media nonbreaking",
             "table contextmenu directionality emoticons paste textcolor filemanager"
       ],
       toolbar1: "undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | styleselect",
       toolbar2: "| filemanager | link unlink anchor | image media | forecolor backcolor  | print preview code | tools | sizeselect | fontselect | fontsizeselect",
       image_advtab: true ,

       external_filemanager_path:"/javascript/responsivefilemanager/responsivefilemanager/",
       filemanager_title:"Responsive Filemanager" ,
       external_plugins: { "filemanager" : "/javascript/responsivefilemanager/responsivefilemanager/plugin.min.js"}
     });
</script>-->