<div class="page-header">
    <h1><?php eh($titulo) ?></h1>
</div>
<div class="row">
    <div class="span3">
        <?php View::partial('backend/menus/recursos') ?>
    </div>
    <div class="span8 span-derecho" >
        <div id="res-form-ajax"><?php View::content() ?></div>
        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
        <?php //echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
        <?php echo Form::hidden('recurso.id') ?>
        <div class="row">
            <div class="span2">
                <label for="recurso_modulo">Modulo : </label>
            </div>
            <div class="span2">
                <label for="recurso_controlador">Controlador * :</label>
            </div>
            <div class="span2">
                <label for="recurso_accion">Ação  : </label>
            </div>
        </div>
        <div class="row control-group">
            <div class="span2">
                <?php echo Form::text('recurso.modulo', 'class="span2"') ?>
            </div>
            <div class="span2">
                <?php echo Form::text('recurso.controlador', 'class="span2"') ?>
            </div>
            <div class="span2">
                <?php echo Form::text('recurso.accion', 'class="span2"') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="recurso_descripcion">Descrição * : </label>
            <?php echo Form::textarea('recurso.descripcion', 'class="span4"') ?>
            </div>
            <div class="control-group">
                <label class="control-label" for="menus_activo">Ativo (Visible) : </label>
            <?php echo Form::select('recurso.activo', array('1' => 'Sim', '0' => 'Não')) ?>
            </div>
            <div class="form-actions">
            <?php echo Form::submit('Guardar Dados', 'class="btn btn-primary"') ?>
            <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
            </div>
        <?php echo Form::close() ?>
    </div>
</div>
