<div class="page-header">
    <h1><?php eh($titulo) ?></h1>
</div>
<div class="row">
    <div class="span3">
        <?php View::partial('website/menus/portifolio') ?>
    </div>
    <div class="span8 span-derecho" >
        <div id="res-form-ajax"><?php View::content() ?></div>
        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
        <?php //echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
        <?php echo Form::hidden('portifolio.id') ?>
        <div class="control-group">
            <label class="control-label" for="portifolio_titulo">Titulo*: </label>
            <div class="controls">
                <?php echo Form::text('portifolio.titulo','class="span3"') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="portifolio_menu">Nome Menu*: </label>
            <div class="controls">
                <?php echo Form::text('portifolio.menu','class="span3"') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="portifolio_descricao">Descrição: </label>
            <div class="controls">
                <?php echo Form::textarea('portifolio.descricao',array('class'=>"span5",'rows'=>'3')) ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="portifolio_activo">Ativo(Visible): </label>
            <div class="controls">
                <?php echo Form::select('portifolio.activo', array('1' => 'Si', '0' => 'No')) ?>
            </div>
        </div>
        <hr/>
                <div class="form-actions">
            <?php echo Form::submit('Guardar dados', 'class="btn btn-principal"') ?>
            <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
            </div>
        <?php echo Form::close() ?>
            </div>
        </div>
        
