<div class="page-header">
    <h1>Idiomas</h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<?php
View::partial('website/barra_superior_listas', FALSE, array('texto' => 'Criar Portifolio','opciones'=>FALSE));
$dt = new DataTable($portifolio);
$dt->addHeaders('Id','Nome', 'Menu', 'Descriçao', 'Estado', 'Alterar', 'Excluir');
$dt->addFields('id','titulo', 'menu','descricao');
$dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png','website/portifolio/activar|website/portifolio/desactivar', '', 'activo');
$dt->imgLink('figuras/editar.png', 'website/portifolio/editar');
$dt->imgLinkConfirm('figuras/eliminar.png', 'website/portifolio/eliminar', '', '¿Realmente desea eliminar este idioma?');
echo $dt->render('class="table table-bordered table-striped"');

?>

