<div class="page-header">
    <h1>Usuarios do Sistema</h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div> 
<?php
    View::partial('backend/barra_superior_listas', FALSE, array('texto' => 'Crear Usuario', 'opciones' => FALSE));
    $dt = new DataTable($usuarios);
    $dt->addHeaders('id', 'Login', 'Nomes', 'Correo Electronico', 'Estado', 'Alterar');
    $dt->addFields('id', 'login', 'nombres', 'email');
    $dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png',
            'webmaster/usuarios/activar|webmaster/usuarios/desactivar', '', 'activo');
    $dt->imgLink('figuras/editar.png', 'webmaster/usuarios/editar');
    echo $dt->render('class="table table-bordered table-striped"');
?>