<div class="page-header">
    <h1>Pro Saude Integral</h1>
</div>
<?php View::content() ?>
<fieldset>
    <legend>Você está no painel de Administração, consulte con <strong>ortizmas14@gmail.com</strong> por qualquer duvida no sistema.</legend>
</fieldset>
<h1>TinyMCE Getting Started Guide</h1>
    <form method="post">
        <textarea id="mytextarea"></textarea>
</form>
<?php
view::partial('tinymce');
?>