<?php $res = Load::model('portifolio')->find('limit: 10', 'order: id DESC'); ?>
<?php $actual = Form::getFieldValue('portifolio.id') //vriable con el id del registro que se edita ?>

<ul class="nav nav-tabs nav-stacked visible-desktop">
    <li class="<?php if (!$actual) echo 'active'; ?>">
        <?php echo Html::linkAction("crear", 'Novo Portifolio'); ?>
    </li>
    <?php foreach ($res as $e): ?>
        <li class="<?php if ($e->id == $actual) echo 'active'; ?>">
            <?php $content = h(strtoupper($e->titulo)); ?>
            <?php echo Html::linkAction("editar/$e->id", $content); ?>
        </li>
    <?php endforeach; ?>
    <li>
        <?php echo Html::linkAction("", 'Ver Todos...'); ?>
    </li>
</ul>