<form class="form-horizontal" action="" method="post" role="form">
        <div class="form-group">
            <label for="inputName"class="col-sm-2 control-label">Nome:</label>
            <div class="col-xs-10">
                <input type="text" name="nome" id="nome" class="form-control"  required />
            </div>
        </div>
        <div class="form-group">
            <label for="inputEmail"class="col-sm-2 control-label">Email:</label>
            <div class="col-xs-10">
                <input type="text" name="email" id="email" class="form-control"  required pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"/>
            </div>
        </div>
        <div class="form-group">
            <label for="inputSala" class="col-sm-2 control-label">Sala:</label>
            <div class="col-xs-10">
                <input type="text" name="sala" class="form-control" id="sala" required >
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                    <input name="reclamacao[]" type="checkbox" id="reclamacao" value="Ar condicionado" /> Ar condicionado
                </label>
              </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                    <input name="reclamacao[]" type="checkbox" id="reclamacao" value="Atraso de alunos" /> Atraso de alunos
                </label>
              </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                    <input name="reclamacao[]" type="checkbox" id="reclamacao" value="Barulho no corredor/prédio"  /> Barulho no corredor/prédio
                </label>
              </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                    <input name="reclamacao[]" type="checkbox" id="reclamacao" value="Cabo de áudio"  /> Cabo de áudio
                </label>
              </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                    <input name="reclamacao[]" type="checkbox" id="reclamacao" value="Caixade som"  /> Caixa de som
                </label>
              </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                    <input name="reclamacao[]" type="checkbox" id="reclamacao" value="Entrada e saida de alunos da sala"  /> Entrada e saida de alunos da sala
                </label>
              </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                    <input name="reclamacao[]" type="checkbox" id="reclamacao" value="Iluminacao da sala"  /> Iluminação da sala
                </label>
              </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                    <input name="reclamacao[]" type="checkbox" id="reclamacao" value="Interrupcao da sala"  /> Interrupção da sala
                </label>
              </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                    <input name="reclamacao[]" type="checkbox" id="reclamacao" value="Interrupcao da aula por terceiros"  /> Interrupção da aula por terceiros
                </label>
              </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                    <input name="reclamacao[]" type="checkbox" id="reclamacao" value="Limpieza da lousa"  />  Limpeza da lousa
                </label>
              </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                    <input name="reclamacao[]" type="checkbox" id="checkbox" value="Limpieza da sala"  /> Limpeza da sala
                </label>
              </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                    <input name="reclamacao[]" type="checkbox" id="reclamacao" value="Mantencao da sala"  /> Manutenção da sala
                </label>
              </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                    <input name="reclamacao[]" type="checkbox" id="reclamacao" value="Monitor no corredor"  /> Monitor no corredor
                </label>
              </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                    <input name="reclamacao[]" type="checkbox" id="reclamacao" value="Organizacao do espaco"  /> Organização do espaço
                </label>
              </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                    <input name="reclamacao[]" type="checkbox" id="reclamacao" value="Projector de vidio"  /> Projetor de vidio
                </label>
              </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                    <input name="reclamacao[]" type="checkbox" id="reclamacao" value="Quantidade de carteiras na sala"  /> Quantidade de carteiras na sala
                </label>
              </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" class="btn btn-default" name="enviar" value="enviar">
            </div>
        </div>
    </form>