<?php View::content() ?>
        <div class="row">
            <h3 class="subrayado">CONTATO</h3>
            <h3 style="padding-left: 20px;text-align: center">Deixe seu contato e descubra como ampliar resultados na vida pessoal e profissional</h3>
            <hr>
                <form class="form-horizontal"  action="/contato" method="post" role="form">
                    <input type="hidden" name="url" value="<?php echo $_SERVER['REQUEST_URI'] ?>">
                        <div class="col-md-6">
                            <section class="espacio-left">
                                <div class="form-group">
                                    <input type="text"  name="nome" class="form-control" placeholder="Nome completo" aria-describedby="sizing-addon3" required="">
                                </div>
                                <div class="form-group">
                                    <input type="text" id="movil" name="movil" class="form-control" placeholder="Telefono" aria-describedby="sizing-addon3" required="">
                                </div>
                                <div class="form-group">
                                    <input type="email" name="email" class="form-control" placeholder="E-mail" aria-describedby="sizing-addon3" required="">
                                </div>
                            </section>
                        </div>
                        <div class="col-md-6">
                            <section class="espacio-right">
                                <div class="form-group">
                                    <select id="state-member" name="state" class="form-control state campo_roda">
                                        <option value="">Estado</option>
                                        <option value="AC">AC</option>
                                        <option value="AL">AL</option>
                                        <option value="AM">AM</option>
                                        <option value="AP">AP</option>
                                        <option value="BA">BA</option>
                                        <option value="CE">CE</option>
                                        <option value="DF">DF</option>
                                        <option value="ES">ES</option>
                                        <option value="GO">GO</option>
                                        <option value="MA">MA</option>
                                        <option value="MG">MG</option>
                                        <option value="MS">MS</option>
                                        <option value="MT">MT</option>
                                        <option value="PA">PA</option>
                                        <option value="PB">PB</option>
                                        <option value="PE">PE</option>
                                        <option value="PI">PI</option>
                                        <option value="PR">PR</option>
                                        <option value="RJ">RJ</option>
                                        <option value="RN">RN</option>
                                        <option value="RO">RO</option>
                                        <option value="RR">RR</option>
                                        <option value="RS">RS</option>
                                        <option value="SC">SC</option>
                                        <option value="SE">SE</option>
                                        <option value="SP">SP</option>
                                        <option value="TO">TO</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <textarea name="mesagem" class="form-control" rows="4" required="" placeholder="Mensagem"></textarea>
                                </div>
                            </section>
                        </div>
                    
                    <div class="form-group">
                        <div class="col-sm-10 col-sm-offset-4">
                            <button type="submit" class="btn btn-primary">Enviar Menssagem</button>
                        </div>
                    </div>
                </form>
        </div>
<script type="text/javascript">
	
	jQuery(function($){
	    $("#movil").mask("(99)999-999-999");
	    $("#cpf").mask("999-999-999-99");
	    $("#cep").mask("99.999-999");
	    /*$("#ano").mask("9999");*/
	});
</script>
