		<div class="bs-callout bs-callout-info">
			<h1><?php //echo $titulo; ?></h1>
			<h3>DEZ PRINCÍPIOS PARA A SAÚDE PLENA</h3>
			<img src="/img/psi/projetos/SaudeeLong.jpg" alt="">
			<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
				<div class="panel panel-default">
				    <div class="panel-heading" role="tab" id="headingOne">
					     <h4 class="panel-title">
					        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
					          	VISUALIZE CARTAZ TAMANHO REAL
					        </a>
					     </h4>
				    </div>
				    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
				      	<div class="panel-body">
				      		<a style="background: #fff;" href="/img/psi/projetos/SaUde-e-Longevidade.jpg" title=""><img src="/img/psi/projetos/SaUde-e-Longevidade.jpg" alt=""></a>
				      	</div>
				    </div>
				</div>
			</div>
			<p style="text-align: justify;">O Semin&aacute;rio de Sa&uacute;de e longevidade objetiva ajudar as in&uacute;meras pessoas que sofrem com a sa&uacute;de debilitada sem saber onde buscar ajuda. E uma grande oportunidade para que os ouvintes possam compreender como viver com mais sa&uacute;de e qualidade de vida, usando como fundamentos:</p>
			<ul>
				<li style="text-align: justify;">As FERRAMENTAS NATURAIS DE CURA presentes na natureza, reveladas e orientadas atrav&eacute;s do Esp&iacute;rito de profecia;</li>
				<li style="text-align: justify;">As descobertas cient&iacute;ficas que confirmam a efic&aacute;cia das ferramentas NATURAIS DE CURA;</li>
				<li style="text-align: justify;">As estat&iacute;sticas atuais da incid&ecirc;ncia de doen&ccedil;as relacionadas ao viver sem princ&iacute;pios;</li>
				<li style="text-align: justify;">Os benef&iacute;cios do viver sob esses princ&iacute;pios, promovendo at&eacute; 90% de efic&aacute;cia na resolu&ccedil;&atilde;o de doen&ccedil;as, potencializando o corpo para uma sa&uacute;de mais plena.</li>
			</ul>
			<p><strong>Objetivos</strong></p>
			<ul>
				<li>Realizar Semin&aacute;rios de Sa&uacute;de em todo o territ&oacute;rio Nacional;</li>
				<li>Desenvolver a percep&ccedil;&atilde;o de como se originam as doen&ccedil;as;</li>
				<li>Gerar a compreens&atilde;o da rela&ccedil;&atilde;o entre sa&uacute;de e adora&ccedil;&atilde;o;</li>
				<li>Despertar o desejo de viver de acordo com os princ&iacute;pios naturais de cura para manter ou ganhar a sa&uacute;de perdida;</li>
				<li>Desenvolver a percep&ccedil;&atilde;o da sa&uacute;de como um Minist&eacute;rio;</li>
				<li>Capacitar l&iacute;deres para a pr&aacute;tica pessoal dos dez princ&iacute;pios NATURAIS DE CURA;</li>
				<li>Estimular l&iacute;deres capacitados a desenvolver Semin&aacute;rios de Sa&uacute;de.</li>
			</ul>
			<p><strong>METODOLOGIA</strong></p>
			<ul>
				<li>SEMIN&Aacute;RIO DE SA&Uacute;DE
					<ul>
						<li>A realizar-se em local e data previamente agendado, com anteced&ecirc;ncia m&iacute;nima de 30 dias;</li>
						<li>A s&eacute;rie de palestras come&ccedil;ar&aacute; &agrave;s 10h e terminar&aacute; &agrave;s 18h;</li>
						<li>Cada membro deve convidar uma ou mais pessoas da comunidade, sendo estes doentes ou n&atilde;o;</li>
						<li>O SEMIN&Aacute;RIO ser&aacute; a porta de entrada para novas amizades e relacionamentos com a comunidade;</li>
						<li>Todos os participantes poder&atilde;o se inscrever no site <a href="http://www.prosa&uacute;deintegral.com.br">prosa&uacute;deintegral.com.br</a> para receber orienta&ccedil;&otilde;es de sa&uacute;de de acordo com sua necessidade;</li>
						<li>Consultas particulares personalizadas dever&atilde;o ser previamente agendadas por telefone, Watsapp ou E-mail.</li>
					</ul>
				</li>
			</ul>
			<p><strong>TEMAS DAS PALESTRAS</strong></p>
			<ul>
				<li>SA&Uacute;DE EM UM MUNDO DOENTE: como manter-se com sa&uacute;de plena, desenvolvendo corpo e mente saud&aacute;veis, em um mundo doente.</li>
				<li>SA&Uacute;DE E LONGEVIDADE: DEZ PRINC&Iacute;PIOS PARA SA&Uacute;DE PLENA: os segredos para a sa&uacute;de e longevidade</li>
				<li>Dores nas costas: nunca mais! H&aacute;bitos posturais e suas implica&ccedil;&otilde;es na sa&uacute;de f&iacute;sica e mental</li>
			</ul>
			<p><strong>COORDENA&Ccedil;&Atilde;O DO PROJETO</strong></p>
			<table class="table table-striped">
				<tbody>
					<tr>
						<td width="647">
							<p><strong>&nbsp;</strong><strong>IDENTIFICA&Ccedil;&Atilde;O</strong></p>
						</td>
					</tr>
					<tr>
						<td width="647">
							<p><strong>&nbsp;</strong><strong>NOME: Dr. Edson Barbosa de Oliveira</strong></p>
						</td>
					</tr>
					<tr>
						<td width="647">
							<h5>&nbsp;TITULA&Ccedil;&Atilde;O</h5>
						</td>
					</tr>
					<tr>
						<td width="647">
							<p><strong>&nbsp;</strong><strong>GRADUA&Ccedil;&Atilde;O</strong></p>
							<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Fisioterapia</p>
						</td>
					</tr>
					<tr>
						<td width="647">
							<p><strong>&nbsp;</strong><strong>ESPECIALIZA&Ccedil;&Atilde;O</strong></p>
							<ul>
								<li>P&oacute;s-graduando em Osteopatia de Madri - Universidade Castelo Branco-SP</li>
								<li>P&oacute;s-graduado em Metodologia do Ensino Superior &ndash; Faculdade Adventista da Bahia - BA</li>
								<li>P&oacute;s-graduado em Fisioterapia Manipulativa &ndash; Universidade Gama Filho - SP</li>
							</ul>
						</td>
					</tr>
					<tr>
						<td width="647">
							<p><strong>CURSOS DE APERFEI&Ccedil;OAMENTO</strong></p>
							<ul>
								<li>Forma&ccedil;&atilde;o de Consultor em Ergonomia e Preven&ccedil;&atilde;o &agrave;s LER/DORT &ndash; SP</li>
								<li>Forma&ccedil;&atilde;o em Naturopatia para a Promo&ccedil;&atilde;o da Sa&uacute;de</li>
							</ul>
							<p><strong>CURSOS DE APRIMORAMENTO</strong></p>
							<ul>
								<li>Tratamento Osteop&aacute;tico nas Lombalgias &ndash; IAENE,</li>
								<li>Posturologia &ndash; BA,</li>
								<li>Semiologia da Coluna Vertebral - IAENE</li>
								<li>Fisioterapia nas Disfun&ccedil;&otilde;es Cr&acirc;niomandibulares &ndash; IAENE,</li>
								<li>Integra&ccedil;&atilde;o Sensorial &ndash; IAENE,</li>
								<li>Curso de Per&iacute;cias C&iacute;veis e Trabalhistas em sa&uacute;de ocupacional - Associa&ccedil;&atilde;o Paulista de Medicina</li>
								<li>Curso de Novos Horizontes da Ergonomia &ndash; Associa&ccedil;&atilde;o Paulista de Medicina</li>
								<li>VII Curso de Introdu&ccedil;&atilde;o &agrave; Liga de Ortopedia e Traumatologia &ndash; USP</li>
								<li>Curso de Massoterapia &ndash; Terapia Manual de Ajuste Postural &ndash; 34. ENAF , MG</li>
								<li>Quiropraxia &ndash; T&eacute;cnicas de Terapia Manual das Disfun&ccedil;&otilde;es Musculoesquel&eacute;ticas &ndash; UNASP, SP</li>
								<li>Curso de Drenagem Linf&aacute;tica &ndash; UNASP - SP</li>
								<li>Curso de Terapia Manual e Postural em H&eacute;rnia de disco lombar &ndash; 33. ENAF &ndash; MG</li>
								<li>Curso de Ergonomia Aplicada nos Dist&uacute;rbios Osteomusculares Relac. ao Trabalho &ndash; ENAF &ndash; MG</li>
								<li>Estrat&eacute;gias de Marketing pessoal e profissional</li>
								<li>Outros...</li>
							</ul>
						</td>
					</tr>
					<tr>
						<td width="647">
							<h5>EXPERI&Ecirc;NCIA ACAD&Ecirc;MICA E PROFISSIONAL</h5>
						</td>
					</tr>
					<tr>
						<td width="647">
							<ul>
								<li>Dose anos de experi&ecirc;ncia cl&iacute;nica para tratamento de dores cr&ocirc;nicas, altera&ccedil;&otilde;es posturais, doen&ccedil;as reumatol&oacute;gicas, degenerativas e neurol&oacute;gicas.</li>
								<li>Sete anos de experi&ecirc;ncia como fisioterapeuta na doc&ecirc;ncia para gradua&ccedil;&atilde;o em Fisioterapia. Faculdade Adventista da Bah&iacute;a &ndash; BA.</li>
								<li>Doc&ecirc;ncia para P&oacute;s-gradua&ccedil;&atilde;o em Gest&atilde;o de Pessoas e Sa&uacute;de Coletiva. Fac. Adv. Bah&iacute;a &ndash; BA.</li>
								<li>Sete anos de experi&ecirc;ncia como supervisor de est&aacute;gios em condi&ccedil;&otilde;es traumato-ortop&eacute;dicas e reumatol&oacute;gicas. Faculdade Adventista da Bah&iacute;a &ndash; BA.</li>
								<li>Dose anos de experi&ecirc;ncia em Ergonomia no ambiente de trabalho, no lar e nas AVD&rsquo;s e AVP&rsquo;s.</li>
								<li>Autor da cole&ccedil;&atilde;o de livros <strong>Dores nas Costas: Nunca Mais!</strong></li>
								<li>Conferencista de sa&uacute;de e qualidade de vida em todo territ&oacute;rio nacional.</li>
							</ul>
						</td>
					</tr>
				</tbody>
			</table>
			<p><strong>EQUIPE PROFISSIONAL</strong></p>
			<p style="text-align: justify;">Para que o Semin&aacute;rio de Sa&uacute;de e Longevidade possa existir nos moldes como se apresenta contamos com uma importante equipe de profissionais especializados e atualizados que entendem como se desenvolve a doen&ccedil;a e como preveni-la de forma pr&aacute;tica e natural. Estes participar&atilde;o em Semin&aacute;rios e orienta&ccedil;&otilde;es de sa&uacute;de aos cadastrados.</p>
			<p style="padding-left: 30px;"><strong>A equipe &eacute; composta por:</strong></p>
			<ul style="list-style-type: circle;">
				<li>Fisioterapeutas,</li>
				<li>Psic&oacute;logos (terapias de crian&ccedil;as, fam&iacute;lia, adolescentes, orienta&ccedil;&atilde;o profissional),</li>
				<li>Terapeutas Naturistas,</li>
				<li>Nutr&oacute;logo,</li>
				<li>Nutricionista,</li>
				<li>Educador F&iacute;sico,</li>
				<li>Lider Espiritual</li>
			</ul>
			<p>As duv&iacute;das existentes devem ser comunicadas ao organizador do projeto atrav&eacute;s do site ou telefone.</p>
			<p style="padding-left: 30px;">&nbsp;</p>
		</div>
<?php //View::content(); //muy importante siempre colocar esta linea en alguna parte de la vista. ?>