<table border="0">
<tbody>
<tr>
<td width="300px">
<p><strong>M&Oacute;DULOS:</strong></p>
<p>MOTIVA&Ccedil;&Atilde;O PARA O SUCESSO PROFISSIONAL</p>
<p>GEST&Atilde;O EM QUALIDADE DE VIDA E SA&Uacute;DE NO TRABALHO</p>
<p>PARCEIRO DE NEG&Oacute;CIOS &ndash; O PROFISSIONAL DO FUTURO</p>
<p>GEST&Atilde;O EM PRODUTIVIDADE</p>
<p>FORMANDO UM TIME DE SUCESSO</p>
<p>PESSOAS E SEUS RESULTADOS</p>
<p>GEST&Atilde;O EM TREINAMENTOS</p>
<p>PLANEJAMENTO ESTRAT&Eacute;GICO</p>
<p>EMPREENDEDORISMO DE SUCESSO</p>
<p>GEST&Atilde;O E LIDERAN&Ccedil;A</p>
<p><em><strong>CARGA HOR&Aacute;RIA: 36 HORAS</strong></em></p>
<p><em><strong>DURA&Ccedil;&Atilde;O: 15 A 45 DIAS</strong></em></p>
<p><em><strong>TEMPO: 120min a 180min &nbsp;</strong> &nbsp;</em></p>
</td>
<td width="250px">
<p style="text-align: justify;"><em>" Desenvolver uma GEST&Atilde;O e LIDERAN&Ccedil;A S&Ecirc;NIOR, requer disposi&ccedil;&atilde;o e proatividade desenvolver talentos, gerar resultados a curto prazo, baixo custo e alta qualidade, exige-se profissionais empreendedores, ousados e criativos, que amem desafios e supera&ccedil;&atilde;o de obst&aacute;culos, que inovem solu&ccedil;&otilde;es e realizem SONHOS ".</em></p>
</td>
</tr>
</tbody>
</table>