<div class="page-header">
  <h1>Noticias y eventos</h1>
</div>
<div id="mensajes_flash" >
    <?php View::content() ?>
</div>
<div class="input-append">
  <?php echo Form::open('website/noticiasyeventos/index'); //inicia un formulario que enviara los?>
  Selecionar um setor:
  <?php echo Form::dbSelect('noticiasyeventos.areas_id','titulo',array('areas','find',"conditions: id=1"),'','onChange=submit()')?>
  e um tipo
  <?php $ar2 =array('' => '-- Selecione um Tipo --', 'destaque' => 'Destaque','projetos' => 'Projetos','noticias' => 'Noticias','dicasDeSaude' => 'Dicas de Saúde','analiseDaSaude' => 'Análise de Saúde','loja' => 'Loja Virtual','testimoniais' => 'Testimoniais','parceiros' => 'Parceiros','eventos' => 'Eventos','equipo' => 'Equipo','clinica' => 'Clinica','empresarial' => 'Empresarial','clubVantagens' => 'Club de Vantagens');
    echo Form::Select('noticiasyeventos_tipo', $ar2,'onChange=submit()');?>
  <?php echo Form::close();?>
</div>

    <?php
    View::partial('website/barra_superior_listas', FALSE, array('texto' => 'Criar Seção','opciones'=>FALSE));
    ?>
<ul class="nav nav-tabs">
    <?php
        $n=1;
        foreach($idiomas as $idioma):
    ?>
    <li <?php if($n==1){echo 'class="active"';} ?>><a href="#<?php echo $idioma->code ?>" data-toggle="tab"><?php echo $idioma->nombre ?></a></li>
    <?php
            $n++;
        endforeach;
    ?>
</ul>

<div class="tab-content">

    <div id="pt" class="tab-pane active">

    <?php
    $dt = new DataTable($paginas_es);
    //$dt->addHeaders('Id','Nombre', '/URL_PATH','Redirec.', 'Orden', 'Conten', 'Estado', 'Seccion', 'Editar', 'Eliminar');
    $dt->addHeaders('Id','Creado', 'Modificado','Titulo','posicion', 'Estado', 'Editar', 'Eliminar');
    $dt->addFields('id','created_at','modified_in','titulo','posicion');
    //$dt->imgLink('figuras/ver.png', 'website/paginas/ver');
    $dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png','website/noticiasyeventos/activar|website/noticiasyeventos/desactivar', '', 'activo');
   // $dt->imgLink('figuras/editar.png', 'website/noticiasyeventos/seccion');
    $dt->imgLink('figuras/editar.png', 'website/noticiasyeventos/editar');
    $dt->imgLinkConfirm('figuras/eliminar.png', 'website/noticiasyeventos/eliminar', '', '¿Realmente desea eliminar esta página?');
    echo $dt->render('class="table table-bordered table-striped"');

    ?>

    </div>
    <div id="en" class="tab-pane">

    <?php
    $dt = new DataTable($paginas_en);
    //$dt->addHeaders('Id','Nombre', '/URL_PATH','Redirec.', 'Orden', 'Conten', 'Estado', 'Seccion', 'Editar', 'Eliminar');
    $dt->addHeaders('Id','Creado', 'Modificado','Titulo','posicion', 'Estado', 'Editar', 'Eliminar');
    $dt->addFields('id','created_at','modified_in','titulo','posicion');
    //$dt->imgLink('figuras/ver.png', 'website/paginas/ver');
    $dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png','website/noticiasyeventos/activar|website/noticiasyeventos/desactivar', '', 'activo');
    //$dt->imgLink('figuras/editar.png', 'website/noticiasyeventos/seccion');
    $dt->imgLink('figuras/editar.png', 'website/noticiasyeventos/editar');
    $dt->imgLinkConfirm('figuras/eliminar.png', 'website/noticiasyeventos/eliminar', '', '¿Realmente desea eliminar esta página?');
    echo $dt->render('class="table table-bordered table-striped"');

    ?>

    </div>
</div>

