<div id='cabecera' class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <?php //echo Html::link('', 'Pro Saude Integral', 'class="brand"') ?>
            <div class="nav-collapse pull-right">
                <ul class="nav">
                    <!--<li><?php //echo Html::link('webmaster/usuarios', 'Administración') ?></li>-->
                </ul>
            </div>
        </div>
    </div>
</div>