<div class="page-header">
    <h1><?php eh($titulo) ?></h1>
</div>
<div class="row">
    <div class="span3">
        <?php View::partial('website/menus/idiomas') ?>
    </div>
    <div class="span8 span-derecho" >
        <div id="res-form-ajax"><?php View::content() ?></div>
        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
        <?php //echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
        <?php echo Form::hidden('idiomas.id') ?>
        <div class="control-group">
            <label class="control-label" for="idiomas_nombre">Nombre del idioma*: </label>
            <div class="controls">
                <?php echo Form::text('idiomas.nombre','class="span3"') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="idiomas_code">Código*: </label>
            <div class="controls">
                <?php echo Form::text('idiomas.code','class="span1"') ?><span class="help-inline">(En minuscula. Ej.: es, en, pt)</span>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="idiomas_charset">Charset: </label>
            <div class="controls">
                <?php echo Form::text('idiomas.charset','class="span1"','utf-8') ?><span class="help-inline">(Recomendado: utf-8)</span>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="idiomas_activo">Activo(Visible): </label>
            <div class="controls">
                <?php echo Form::select('idiomas.activo', array('1' => 'Si', '0' => 'No')) ?>
            </div>
        </div>
        <hr/>
                <div class="form-actions">
            <?php echo Form::submit('Guardar datos', 'class="btn btn-principal"') ?>
            <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
            </div>
        <?php echo Form::close() ?>
            </div>
        </div>
        
