<div class="page-header">
	<h1><?php echo $titulo;?></h1>
</div>
<div class="row">
    <div class="span3">
        <?php View::partial('website/menus/informacoes') ?>
    </div>
    <div class="span8 span-derecho form-horizontal" >
    	<div id="res-form-ajax"><?php View::content() ?></div>
 		<?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
        <?php //echo Form::open('crear', 'post', 'class="scaffold"') ?>
    	<div class="control-group form-horizontal">
            <label class="required">Selecione uma Area<em>*</em></label>
            <?php echo Form::dbSelect('informacoes.areas_id','nombre',array('areas','find',"conditions: areas_id= 1"),'- Ninhum -','class="span3" autocomplete="off" required="required"') ?>
        </div>
        <div class="control-group form-horizontal">
            <label class="required">Selecione Grupo de Usuarios<em>*</em></label>
            <?php echo Form::dbSelect('informacoes.usuarios_id','nombres',array('usuarios','find',"conditions: id= id"),'- Ninhum -','class="span3" autocomplete="off" required="required"') ?>
        </div>
        <div class="control-group form-horizontal">
            <label class="required" for="informacoes_titulo">Nome: </label>
            <?php echo Form::text('informacoes.nome','class="span6"') ?>
        </div>
        <div class="control-group form-horizontal">
            <label class="required" for="informacoes_conteudo">Conteudo: </label>
            <div style="clear:both;"></div>
            <?php echo Form::textarea('informacoes.conteudo',array('class'=>"tinymce span6",'rows'=>'20','cols'=>'60')) ?>
        </div>
        <div class="control-group">
            <label class="required">Ativo <em>*</em></label>
            <?php echo Form::select('informacoes.activo',array('1' => 'Si', '0' => 'No'), 'autocomplete="off" required="required" maxlength="12" onkeypress="return permite(event, \'num_car\')"') ?>
        </div>
        <div class="form-actions">
            <?php echo Form::submit('Guardar Dados', 'class="btn btn-principal"') ?>
            <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
        </div>
        <?php echo Form::close() ?>
 	</div>
</div>
<?php
view::partial('tinymce'); 
?>
