<div class="page-header">
	<h1><?php echo $titulo;?></h1>
</div>
<div class="row">
    <div class="span3">
        <?php View::partial('webupeu/menus/archivos') ?>
    </div>
    <div class="span8 span-derecho form-horizontal" >
    	<div id="res-form-ajax"><?php View::content() ?></div>
    	<?php //echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
 			<?php echo Form::openMultipart(); ?>
      <?php //echo Form::open('crear', 'post', 'class="scaffold"') ?>
    	<div class="control-group form-horizontal">
        <label class="required">Elegir carpeta <em>*</em></label>
        <?php echo Form::dbSelect('archivos.carpetas_id','nombre',array('carpetas','find',"conditions: areas_id=".Session::get('SITEID')),'- Ninguna -','class="span3" autocomplete="off" required="required"') ?>
        <small>  Necesita crear una carpeta en su site.</small>
      </div>
      <!--<div class="control-group">-->
            <?php if (isset($usuario)) {?>                
                    <?php foreach ($usuario as  $value) {
                        $nombre = $value->nombres;
                        $id = $value->id;
                    }?>
            <?php } ?>
        <!--<label class="required">Id Usuarios <em>*</em></label>-->
        <?php echo Form::hidden('archivos.usuarios_id','readonly="readonly" value="$id"',"$id") ?>
        <?php //echo Form::text('archivos.usuarios_id', 'autocomplete="off" autofocus="autofocus"  required="required" maxlength="30" onkeypress="return permite(event, \'car\')"') ?>
      <!--</div>-->
      <!--<div class="control-group">
        <label class="required">Url  <em>*</em></label>
        <?php echo Form::text('archivos.urlname', 'autocomplete="off" autofocus="autofocus"  required="required" maxlength="30" onkeypress="return permite(event, \'car\')"') ?>
      </div>-->
      <!--<div class="control-group">
        <label class="required">Tamaño <em>*</em></label>
        <?php echo Form::text('archivos.tamanho', 'autocomplete="off" required="required" maxlength="12" onkeypress="return permite(event, \'num_car\')"') ?> 
      </div>-->
      <!--<div class="control-group">
        <label class="required">Tipo <em>*</em></label>
        <?php echo Form::text('archivos.tipo', 'autocomplete="off" required="required" maxlength="12" onkeypress="return permite(event, \'num_car\')"') ?>
      </div>-->
      <div class="control-group">
        <label class="required">Activo <em>*</em></label>
        <?php echo Form::select('archivos.activo',array('1' => 'Si', '0' => 'No'), 'autocomplete="off" required="required" maxlength="12" onkeypress="return permite(event, \'num_car\')"') ?>
      </div>
    	
      <div class="control-group">
        <label class="required">Ingrese una imagen .jpg .gif ó .png:</label>
          <?php echo Form::file('archivo', 'required="required" maxlength="500"') ?>
      </div>
      <div class="form-actions">
          <?php echo Form::submit('Guardar datos', 'class="btn btn-principal"') ?>
          <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
      </div>
      
    
 <?php echo Form::close() ?>
 	</div>
</div>
 


 