<!DOCTYPE html>
<html lang="en">
<head>
    <?php View::helpers('website/libhelper'); ?>
    <?php View::partial('psite/cssDefault') ?>
</head>
<body>
    <?php View::partial('psite/analyticstracking') ?>
    <!-- ====================================================
    header section -->
    <header class="top-header">
        <div class="container">
            <div class="row">
                <div class="col-xs-4 header-logo">
                    <br>
                    <a href="index.html"><?php echo Html::img('psi/logo.png','Logo',array('class'=>'img-responsive logo')) ?></a>
                </div>
                <div class="col-md-12">
                    <nav class="navbar navbar-default">
                      <div class="container-fluid nav-bar">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                          </button>
                        </div>
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                          <ul class="nav navbar-nav navbar-right">
                            <li><a class="menu active" href="/#home" >Home</a></li>
                            <?php LibHelper::MenuHeaderConteudo(); ?>
                          </ul>
                        </div>
                        <!-- /navbar-collapse -->
                      </div><!-- / .container-fluid -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- end of header area -->
    <!-- =========================
       Portfolio
    ============================== -->
    <section id="portfolio" class="portfolio padding-large text-center">
        <div id="content-title">
            <div class="contact-heading text-center">
                <div class="container margin-bottom-mediumClinica">
                    <div class="row margin-bottom-mediumClinica wow fadeInUp">
                        <h2>
                            ESPECIALIDADES
                            <strong class="main-color bold-text">CLINICA</strong>
                        </h2>
                        <!--<div class="col-md-10 col-md-offset-1">
                            <div class="subtitle">ESPECIALIDADES - CLINICA</div>
                        </div>-->
                    </div>
                </div>
            </div>
        </div>
        <div class="portfolio-wrapper photography">
            <?php libHelper::clinica() ?>
            <!--<div class="portfolio-item print">
                <div class="portfolio">
                    <a href="/img/psi/especialidades/portfolio-1.jpg" data-lightbox-gallery="portfolio">
                        <img src="/img/psi/especialidades/portfolio-1.jpg" alt="Portfolio 1"/>
                        <div class="portfolio-overlay hvr-rectangle-out">
                            <h2 class="margin-bottom-small">
                                <strong class="white-color bold-text">FISIOTERAPIA</strong>
                            </h2>
                            <div class="button">VER ESPECIALIDADE</div>
                        </div>
                    </a>
               </div>
            </div>
            <div class="portfolio-item photography">
               <div class="portfolio">
                  <a href="/img/psi/especialidades/portfolio-2.jpg" data-lightbox-gallery="portfolio">
                    <img src="/img/psi/especialidades/portfolio-2.jpg" alt="Portfolio 2"/>
                    <div class="portfolio-overlay hvr-rectangle-out">
                        <h2 class="margin-bottom-small">
                            <strong class="white-color bold-text">NATUROPATIA</strong>
                        </h2>
                        <div class="button">VER ESPECIALIDADE</div>
                    </div>
                  </a>
               </div>
            </div>
            <div class="portfolio-item photography">
               <div class="portfolio">
                  <a href="/img/psi/especialidades/portfolio-3.jpg" data-lightbox-gallery="portfolio">
                    <img src="/img/psi/especialidades/portfolio-3.jpg" alt="Portfolio 1"/>
                    <div class="portfolio-overlay hvr-rectangle-out">
                        <h2 class="margin-bottom-small">
                            <strong class="white-color bold-text">PSICOTERAPIA</strong>
                        </h2>
                        <div class="button">VER ESPECIALIDADE</div>
                    </div>
                  </a>
               </div>
            </div>
            <div class="portfolio-item photography">
               <div class="portfolio">
                  <a href="/img/psi/especialidades/portfolio-4.jpg" data-lightbox-gallery="portfolio">
                    <img src="/img/psi/especialidades/portfolio-4.jpg" alt="Portfolio 1"/>
                    <div class="portfolio-overlay hvr-rectangle-out">
                        <h2 class="margin-bottom-small">
                            Our
                            <strong class="white-color bold-text">Portfolios</strong>
                        </h2>
                        <div class="button">View Project</div>
                    </div>
                  </a>
               </div>
            </div>
            <div class="portfolio-item photography">
               <div class="portfolio">
                  <a href="/img/psi/especialidades/portfolio-3.jpg" data-lightbox-gallery="portfolio">
                    <img src="/img/psi/especialidades/portfolio-3.jpg" alt="Portfolio 1"/>
                    <div class="portfolio-overlay hvr-rectangle-out">
                        <h2 class="margin-bottom-small">
                            Our
                            <strong class="white-color bold-text">Portfolios</strong>
                        </h2>
                        <div class="button">View Project</div>
                    </div>
                  </a>
               </div>
            </div>
            <div class="portfolio-item photography">
               <div class="portfolio">
                  <a href="/img/psi/especialidades/portfolio-4.jpg" data-lightbox-gallery="portfolio">
                    <img src="/img/psi/especialidades/portfolio-4.jpg" alt="Portfolio 1"/>
                    <div class="portfolio-overlay hvr-rectangle-out">
                        <h2 class="margin-bottom-small">
                            Our
                            <strong class="white-color bold-text">Portfolios</strong>
                        </h2>
                        <div class="button">View Project</div>
                    </div>
                  </a>
               </div>-->
            </div>
        </div>
        <!--<a href="#" class="button light margin-top-medium margin-bottom-medium hvr-grow"><i class="icon-reload"></i> Load More</a>-->
    </section>
    <!-- *** end Portfolio *** -->
    <!-- contact section starts here -->
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="contact-caption clearfix">
                    <div class="contact-heading text-center">
                        <h2>Contato</h2>
                    </div>
                    <div class="col-md-5 contact-info text-left">
                        <h3>Informação de Contato</h3>
                        <div class="col-xs-10 col-sm-10 col-md-10">
                            <div class="info">
                                <h5>Ligue-nos</h5><br>
                                <dd>(75) 3414-2018</dd>
                            </div>
                            <div class="info">
                                <h5>Watsapp</h5><br>
                                <dd>(75) 9 91160476</dd>
                            </div>
                            <div class="info">
                                <h5>Encontre-nos</h5><br>
                                <dd>Rua Plácido Pita, 50 , Capoeirocu – Cachoeira-BA</dd>
                            </div>
                            <div class="info">
                                <h5>E-mail</h5><br>
                                <dd>contato@prosaudeintegral.com.br</dd>
                                <dd>secretaria@prosaudeintegral.com.br</dd>
                                <dd>administrativo@prosaudeintegral.com.br</dd>
                            </div>
                        </div>
                        <div class="col-md-2 hidden-xs">
                            <div class="info-detail">
                                <ul><li><i class="fa fa-phone"></i></li></ul>
                                <ul><li><i class="fa fa-whatsapp"></i></li></ul>
                                <ul><li><i class="fa fa-map-marker"></i></li></ul>
                                <ul><li><i class="fa fa-envelope"></i></li></ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-md-offset-1 contact-form">
                        <h3>Deixe-nos uma mensagem </h3>
                        <form class="form">
                            <input class="name" type="text" placeholder="Digite seu Nome">
                            <input class="email" type="email" placeholder="Digite seu E-mail">
                            <input class="phone" type="text" placeholder="Telefone" width="20%">
                            <input class="watsap" type="text" placeholder="WatsApp">
                            <textarea class="message" name="message" id="message" cols="30" rows="5" placeholder="Mensagem"></textarea>
                            <input class="submit-btn" type="submit" value="ENVIAR">
                            <input class="reset-btn" type="reset" value="LIMPAR">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end of contact section -->
    <div id="newslleter" class="newsletter">
        <div class="container">
            <div class="contact-heading text-center">
                <h3>TRABALHE CONOSCO</h3>
                <span>Entre em contato para ver as condições.</span>
                <hr>
            </div>
            <div class="row">
                <form class="form-inline" action="" method="get" style="text-align: center">
                    <div class="form-group">
                        <input type="text" name="nome" value="" placeholder="Digite seu nome" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <input type="email" name="" value="" placeholder="Digite seu e-mail" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <input class="submit-btn" type="submit" value="ENVIAR">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- footer starts here -->
    <footer class="footer clearfix">
        <div class="container">
            <div class="row">
                <div class="col-xs-6 footer-para">
                    <p>&copy; Pro Saude Integral</p>
                </div>
                <div class="col-xs-6 text-right">
                    <a href=""><i class="fa fa-facebook"></i></a>
                    <a href=""><i class="fa fa-twitter"></i></a>
                    <a href=""><i class="fa fa-skype"></i></a>
                </div>
            </div>
        </div>
    </footer>
    <!-- script tags
    ============================================================= -->
    <?php View::partial('psite/jsDefault') ?>
</body>
</html>