<!DOCTYPE html>
<html lang="pt-BR">
<head>
	<?php View::helpers('website/libhelper'); ?>
	<?php View::partial('psite/cssDefault') ?>
	<!--<link href='http://fonts.googleapis.com/css?family=Open+Sans:600italic,400,800,700,300' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=BenchNine:300,400,700' rel='stylesheet' type='text/css'>-->
</head>
<body>
	<?php View::partial('psite/analyticstracking') ?>
	<?php View::content() ?>
	<!-- ======header section -->
	<header class="top-header">
		<div class="container-page pt-3 pb-2">
			<div class="row">
				<div class="col-xs-6 col-sm-6 col-md-3 col-lg-3">
					<a href="/"><?php echo Html::img('psi/logo/logo.png','PSI',array('class'=>'img-fluid')) ?></a>
				</div>
				<div class="col-xs-6 col-sm-6 col-md-9 col-lg-9">
					<nav class="navbar navbar-expand-lg navbar-light">
						<!-- <a class="navbar-brand" href="#">Navbar</a> -->
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-home" aria-controls="nav-home" aria-expanded="false" aria-label="Toggle navigation">
							<span class="navbar-toggler-icon"></span>
						</button>
					    <!-- Collect the nav links, forms, and other content for toggling -->
					    <div class="collapse navbar-collapse" id="nav-home">
					    	<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
						    	<li></li>
						    </ul>
						    <ul class="navbar-nav">
						    	<li class="nav-item nav-link"><a class="nav-link text-dark text-uppercase font-weight-bold" href="#home" >Home</a></li>
						    	<?php
						    		Libhelper::MenuHeader();
						    	?>
						    </ul>
					    </div>
					    <!-- /navbar-collapse -->
					</nav>
				</div>
			</div>
		</div>
	</header>
	<!-- end of header area -->

	<!--Slide-->
	<section class="section-slide pb-1" id="inicio">
		<div class="container-fluid">
			<div class="container-page">
				<div class="row">
					<div class="col-md">
						<div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
							<!-- Wrapper for slides -->
							<div class="carousel-inner" role="listbox">
								<?php
								Libhelper::destaque();
								?>
							</div>
							<!-- Controls -->
							<a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
								<span class="fa fa-chevron-circle-left fa-2x" aria-hidden="true"></span>
								<span class="sr-only">Previous</span>
							</a>
							<a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
								<span class="fa fa-chevron-circle-right fa-2x" aria-hidden="true"></span>
								<span class="sr-only">Next</span>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--start-slide-->
	
	<!--Inicio treinamentos style="background-image: url(/img/psi/bg/bg-4.jpg);"-->
	<section class="treinamentos pt-5 pb-5">
		<div class="container-fluid">
			<div class="container-page">
				<div class="text-center pb-5">
					<h2 class="line-one">Treinamentos</h2>
				</div>
				<div class="row justify-content-center">
					<?php Libhelper::projetos() ?>
				</div>
			</div>
	    </div>
	</section>
	<!----//End-treinamentos----->

	<!--Inicio treinamentos-->
	<section class="palestras pt-4 pb-4">
		<div class="container-fluid">
			<div class="container-page">
				<div class="text-center">
					<h2>Palestras</h2>
				</div>
				<div class="row justify-content-center">
					<?php Libhelper::palestras() ?>
				</div>
			</div>
		</div>
	</section>
	<!----//End-treinamentos----->
	<div class="clearfix">
		
	</div>

	<!--=============Inicio Dicas e Libros ================-->
	<!-- <div id="loja">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 animated fadeInRight">
					<h2>Dicas de Saúde</h2>
					<?php //Libhelper::dicasDeSaude() ?>
				</div>
				<div class="col-lg-3 animated fadeInRight">
					<h2 style="font-size: 1.8em;margin-bottom:14px;">CADASTRO CLIENTE</h2>
					<?php //Libhelper::analiseDaSaude() ?>
				</div>
				<div class="col-lg-5 animated fadeInRight">
					<h2>Loja Virtual</h2>
						<?php //Libhelper::lojaVirtual() ?>
					</div>
			</div>
		</div>
	</div> -->
	<!--=============End Dicas e Libros ================-->

	<!-- =========================Testimonial============================== -->
    <!--<section id="testimonial" class="testimonial padding-large white-color text-center">
        <div class="container">
            <div class="row">
                <h2 class="margin-bottom-medium">Nossos <strong class="bold-text">Testimoniais</strong></h2>
                <div class="col-md-10 col-md-offset-1">
                    <div id="testimonial-carousel" class="owl-carousel owl-theme testimonial-carousel">
                        <div class="item margin-bottom-small">
                            <p>This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit..</p>
                            <div class="client margin-top-medium clearfix">
                                <img src="img/psi/testimonial/testimonial-1.jpg" height="50" width="50" alt="Client Image">
                                <ul class="client-info main-color">
                                    <li><strong>John Doe</strong></li>
                                    <li>Co-Founder, Envato</li>
                                </ul>
                            </div>
                        </div>
                        <div class="item">
                            <p>This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit..</p>
                            <div class="client margin-top-medium">
                                <img src="img/psi/testimonial/testimonial-2.jpg" alt="Client Image" class="grayscale">
                                <ul class="client-info main-color">
                                    <li>John Doe</li>
                                    <li>Co-Founder, Envato</li>
                                </ul>
                            </div>
                        </div>
                        <div class="item">
                            <p>This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit..</p>
                            <div class="client margin-top-medium">
                                <img src="img/psi/testimonial/testimonial-1.jpg" alt="Client Image" class="grayscale">
                                <ul class="client-info main-color">
                                    <li>John Doe</li>
                                    <li>Co-Founder, Envato</li>
                                </ul>
                            </div>
                        </div>
                        <div class="item">
                            <p>This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit..</p>
                            <div class="client margin-top-medium">
                                <img src="img/psi/testimonial/testimonial-2.jpg" alt="Client Image" class="grayscale">
                                <ul class="client-info main-color">
                                    <li>John Doe</li>
                                    <li>Co-Founder, Envato</li>
                                </ul>
                            </div>
                        </div>
                        <div class="item">
                            <p>This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit..</p>
                            <div class="client margin-top-medium">
                                <img src="img/psi/testimonial/testimonial-1.jpg" alt="Client Image" class="grayscale">
                                <ul class="client-info main-color">
                                    <li>John Doe</li>
                                    <li>Co-Founder, Envato</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>-->
    <!-- *** end Testimonial *** -->

	<!-- contact section starts here -->
	<section id="contato">
		<div class="container-fluid">
			<div class="container-page"> 
				<div class="contact-caption">
					<div class="text-center pt-5 pb-5">
						<h1 class="text-white">Contato</h1>
					</div>
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
							<div class="contact-info text-right">
								<h3>Informação de Contato</h3>
								<div class="row">
									<div class="col-xs-10 col-sm-10 col-md-10">
										<div class="info pt-4">
											<h5>Ligue-nos</h5><br>
											<dd>(75) 3414-2018</dd>
										</div>
										<div class="info">
											<h5>Watsapp</h5><br>
											<dd>(75) 9 91160476</dd>
										</div>
										<div class="info">
											<h5>Encontre-nos</h5><br>
											<dd>Rua Plácido Pita, 50 , Capoeirocu – Cachoeira-BA</dd>
										</div>
										<div class="info">
											<h5>E-mail</h5><br>
											<dd>contato@prosaudeintegral.com.br</dd>
											<dd>secretaria@prosaudeintegral.com.br</dd>
											<dd>administrativo@prosaudeintegral.com.br</dd>
										</div>
									</div>
									<div class="col-md-2 d-none d-md-block">
										<div class="info-detail">
											<ul><li><i class="fa fa-phone"></i></li></ul>
											<ul><li><i class="fa fa-whatsapp"></i></li></ul>
											<ul><li><i class="fa fa-map-marker"></i></li></ul>
											<ul><li><i class="fa fa-envelope"></i></li></ul>
										</div>
									</div>
								</div>
							</div>
						</div>

						<div class="col-xs-12 col-md-6 col-lg-6">
							<div class="contact-form">
								<h3>Deixe-nos uma mensagem </h3>
								<form class="form" action="contato" method="post">
		                            <input type="hidden" name="url" value="<?php echo $_SERVER['REQUEST_URI'] ?>" placeholder="">
									<input class="name" type="text" name="nome" placeholder="Digite seu Nome" required >
									<input class="email" type="email" name="email" placeholder="Digite seu E-mail" required >
									<input class="phone" type="text" name="phone" id="phone" placeholder="Telefone" width="20%" required >
									<input class="watsap" type="text" name="whatsapp" placeholder="WhatsApp">
									<textarea class="message" name="message" id="message" cols="30" rows="5" placeholder="Mensagem" required></textarea>
									<input class="submit-btn" type="submit" value="ENVIAR" >
									<input class="reset-btn" type="reset" value="LIMPAR" >
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- end of contact section -->
	<div id="newslleter" class="newsletter">
		<div class="container-fluid">
			<div class="contact-heading text-center">
				<h3>TRABALHE CONOSCO</h3>
				<span>Entre em contato para ver as condições.</span>
				<hr>
			</div>
			<div class="row">
				<div class="col-md d-flex justify-content-center">
					<form class="form-inline" action="contato" method="post">
						<input type="hidden" name="url" value="<?php echo $_SERVER['REQUEST_URI'] ?>" placeholder="">
						<div class="form-group">
							<input type="text" name="nome" value="" placeholder="Digite seu nome" class="form-control" required>
						</div>
						<div class="form-group">
							<input type="email" name="email" value="" placeholder="Digite seu e-mail" class="form-control" required>
						</div>
						<div class="form-group">
							<input class="submit-btn" type="submit" value="ENVIAR">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<!-- footer starts here -->
	<footer class="footer clearfix">
		<div class="container-fluid">
			<div class="row">
				<div class="col-xs-6 footer-para">
					<p>&copy; Pro Saude Integral</p>
				</div>
				<div class="col-xs-6 float-right">
					<a href=""><i class="fa fa-facebook"></i></a>
					<a href=""><i class="fa fa-twitter"></i></a>
					<a href=""><i class="fa fa-skype"></i></a>
				</div>
			</div>
		</div>
	</footer>
	<!-- script tags
	============================================================= -->
	<?php View::partial('psite/jsDefault') ?>
	<script type="text/javascript">
		$(document).ready(function(){
		    $("input").blur(function(){
		     if($(this).val() == "")
		         {
		             $(this).css({"border-color" : "#F00", "padding": "2px"});
		         }
		    });
		})
		jQuery(function($){
		    $("#phone").mask("(99)999-999-999");
		    /*$("#cpf").mask("999-999-999-99");
		    $("#cep").mask("99.999-999");
		    $("#ano").mask("9999");*/
		});
	</script>
</body>
</html>