<!DOCTYPE html>
<html>
<head>
	<meta content="charset=utf-8">
	<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
    <!-- estilos locales -->
    <link rel="stylesheet" href="/css/website/publicidad/styles.css" type="text/css" media="screen" />
    <!-- FlexSlider archivos -->
    <link rel="stylesheet" type="text/css" href="/css/website/publicidad/flexslider.css" />

    <!--Ultimas Publicidad-->
	<script type="text/javascript" src="/javascript/website/publicidad/jquery.flexslider-min.js"></script>
	<!-- html5.js - IE  9 -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

	<!-- funcion para conectar el FlexSlider -->
	<script type="text/javascript">
		$(window).load(function() {
			$('.flexslider').flexslider();
		});
	</script>
</head>
<section id="">
		   <div class="flexslider">
			    <ul class="slides">
			    	<li>
			    		<img src="uploads/radioupeu/publicidad1/1.png" />
			    		<p class="flex-caption">Texto Caption 1 - Lorem</p>
			    	</li>
			    	
			    	<li>
			    		<img src="uploads/radioupeu/publicidad1/2.png"/>
		                <p class="flex-caption">Texto Caption 2 - Lorem Ipsum</p>
			    	</li>
			    	<li>
			    		<img src="uploads/radioupeu/publicidad1/3.png" />
		                <p class="flex-caption">Texto Caption 3 - Lorem Ipsum Amat</p>
			    	</li>
			    </ul>
			  </div>
		 </section>
</html>