<meta charset="UTF-8">
<title>Pro Saude Integral</title>
<meta name="viewport" content="width=device-width">
<meta name="description" content="Pro Saude Integral">
<meta name="author" content="Pro Saude Integral">
<link rel="shortcut icon" href="/img/favicon.ico">
<?php
    //Tag::css('psi/font-awesome.min');
    echo '<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">';
    echo '<link rel="stylesheet" href="/libs/bootstrap/css/bootstrap.min.css">';
    //Tag::css('psi/bootstrap.min');
    Tag::css('psi/docs.min');
    Tag::css('psi/style');
    Tag::css('psi/psi.min');
    Tag::css('psi/owl.carousel');
    Tag::css('psi/owl.theme');
    Tag::css('psi/nivo-lightbox');
    Tag::css('psi/nivo-lightbox-default');
    //Tag::css('psi/theme-style');
    Tag::css('psi/template');
    Tag::css('psi/animate.min');
    Tag::css('psi/quem');
    echo Html::includeCss();
    //echo Tag::js('psi/jquery-2.1.1');
    //echo '<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>';
?>
<!--<script src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js'></script>-->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
