<div class="header_box">
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="navbar-header">
            <button type="button" id="nav-toggle" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        </div>
        <div id="main-nav" class="collapse navbar-collapse navStyle">
            <ul class="nav navbar-nav" id="mainNav">
                <?php Menu::sidebarmenu(); ?>
                <!--<li class="active"><a href="#carousel" class="scroll-link">Home</a></li>
                <li><a href="#aboutUs" class="scroll-link">About Me</a></li>
                <li><a href="#service" class="scroll-link">Our Services   </a></li>
                <li><a href="#Portfolio" class="scroll-link">Gallery</a></li>
                <li><a href="#experience" class="scroll-link">Testimonial</a></li>
                <li><a href="#contact" class="scroll-link">Contact</a></li>-->
            </ul>
        </div>
    </nav>
</div>