<li><a href="/" title="Crescer Brasil">Home</a></li>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Relacionamento <span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li><a style="text-align: center">Fones: <br> <h4>(71) 99248-2626</h4></a> </li>
        <li><a target="_blank" href="https://accounts.google.com/ServiceLogin?sacu=1&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&hl=pt-BR&service=mail#identifier"  style="text-align: center">E-mails: <br>contato@icrescerbrasil.com.br</a> </li>
        <li role="separator" class="divider"></li>
        <!--<li class="dropdown-header">Nav header</li>-->
        <li><a href="/contatos" title="Consulte suas duvidas"><button type="submit" class="btn btn-primary btn-block">Contato</button></a></li>
        <!--<li><a href="/" title=""><button type="submit" class="btn btn-primary btn-block">Email</button></a></li>-->
    </ul>
</li>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Agenda <span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li><a style="text-align: center"><br> <h4>International em Life Coaching Certification (ILCC)</h4></a> </li>
        <li><a   style="text-align: center">Local: Brasília Imperial hotel SHS QD 03, BLOCO H</a> </li>
        <li><a style="text-align: center">Data e horário: 10 a 17/04/2016 - das 8h as 20h30.123</a></li>
    </ul>
</li>