<div class="page-header">
    <h1>Enlaces
    </h1>
</div>
<div id="mensajes_flash" >
    <?php View::content() ?>
</div>
<div class="input-append">
  <?php echo Form::open('website/enlaces/index'); //inicia un formulario que enviara los?>
  Seleccionar una area:
  <?php echo Form::dbSelect('enlaces.areas_id','titulo',array('areas','find',"conditions: id= 1"/*.Session::get('SITEID')*/),'','onChange=submit()')?>
  y una posicion
  <?php $ar2 =array('clube-de-vantagens' => 'Clube de Vantagens', 'propaganda' => 'Propaganda', 'propaganda-top' => 'Propaganda Top');
    echo Form::Select('enlaces_posicion', $ar2,'onChange=submit()');?>
  <?php echo Form::close();?>
</div>

<?php
View::partial('website/barra_superior_listas', FALSE, array('texto' => 'Crear enlace','opciones'=>FALSE));
?>
<?php
  $dt = new DataTable($enlaces);
  $dt->addHeaders('N&ordm;','Nombre','Descripción','Posicion','Editar', 'Eliminar');
  $dt->addFields('id','nombre','descripcion');
  $dt->addFields('posicion');
  /*$dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png','website/sitios/activar|website/sitios/desactivar', '', 'activo');*/
  $dt->imgLink('figuras/editar.png', 'website/enlaces/editar');
  $dt->imgLinkConfirm('figuras/eliminar.png', 'website/enlaces/eliminar', '', '¿Realmente desea eliminar este sitio?');
  echo $dt->render('class="table table-bordered table-striped"');
?>
