<div class="page-header">
    <h1>Redes sociales</h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<?php
View::partial('website/barra_superior_redessociales', FALSE, array('texto' => 'Crear redes sociales','opciones'=>FALSE));
?>
<h2>Radio UPeU</h2>
<?php
  $dt = new DataTable($redessociales);
  $dt->addHeaders('N&ordm;','Titulo','Url','Ventana','Posicion','Estado','Editar', 'Eliminar');
  $dt->addFields('id');
  $dt->addFields('nombre','url','target');
  $dt->addFields('posicion');
  $dt->imgLink('figuras/circulo_rojo.png|figuras/circulo_verde.png','website/enlaces/redsocial_activar|website/enlaces/redsocial_desactivar', '', 'activo');
  $dt->imgLink('figuras/editar.png', 'website/enlaces/redessociales_editar');
  $dt->imgLinkConfirm('figuras/eliminar.png', 'website/enlaces/redessociales_eliminar', '', '¿Realmente desea eliminar este sitio?');
  echo $dt->render('class="table table-bordered table-striped"');
?>
